### ISSUE TITLE
[Bug] Cannot find module '@anansi/eslint-plugin' with anansi-js generator 

### ISSUE THREAD

**Issue by kmartinezmedia** [ntucker/anansi#25]
Steps to reproduce:
1. Run `npm install -g yo @anansi/generator-js`

![image](https://user-images.githubusercontent.com/6308123/74611178-6f4bed80-50ae-11ea-882b-4b5037f9d12d.png)

2. Go through yeoman walkthrough: select Application, enter email, add included features (storybook, testing, CI), select Legacy react mode.

![image](https://user-images.githubusercontent.com/6308123/74611103-f0ef4b80-50ad-11ea-9f3c-fc57bae2657a.png)

**Comment by ntucker** [comment]
Trying to repro now
