### ISSUE TITLE
[Bug] Hatch-anasi throwing missing tsconfig.json for library project generation

### ISSUE THREAD

**Issue by kmartinezmedia** [ntucker/anansi#28]
This only appears to be an issue with library project generation. Application generation works correctly.

Steps to reproduce:
1. Run npm install -g yo @anansi/generator-js
2. Select Library
3. Enter github username
4. Select all features (Storybook, testing, CI)
5. Get missing tsconfig.json error below

![image](https://user-images.githubusercontent.com/6308123/74803730-eb9f2600-5292-11ea-9739-6fac09ef3111.png)

**Comment by ntucker** [comment]
does that file - the tsconfig.json - exist? This is a weird error because I see it on my local instance at least
